name: Caring Dev
author:
  display_name: Raphael Schweizer
  email: code@caringdev.ch
  twitter: _Caring_Dev_
markdown: kramdown
highlighter: rouge
permalink: /blog/:year/:month/:title/
plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude: [ Gemfile, Gemfile.lock ]