FROM mcr.microsoft.com/vscode/devcontainers/ruby:1.1.8-3.3-bookworm

ENV LANG=en_US.UTF-8 \
    LANGUAGE=en_US:en \
    TZ=Etc/UTC \
    LC_ALL=en_US.UTF-8 \
    LANG=en_US.UTF-8 \
    LANGUAGE=en_US

RUN gem install bundler
